### ISSUE TITLE
Connect Wallet when issuing credential

### ISSUE THREAD

**Issue by philip-raschke** [philip-raschke/educredentials#9]
Instead of copying the invitation data, does the QR code displayed work for connecting to the issuer?

**Comment by Ph4t3** [comment]
The QR code in moodle does not work. What works to connect to the issuer from the wallet is the invitation URL created in the Faber Agent bash. This invitation URL as a QR code works for the invitation and should replace the QR code that is currently displayed in Moodle.

**Comment by Ph4t3** [comment]
Resolved. QR code displayed by the plugin page uses the invitation url and connection works with the BC wallet app.

**Comment by Ph4t3** [comment]
Resolved. QR code displayed by the plugin page uses the invitation url and connection works with the BC wallet app.
